# -*- coding: utf-8 -*-
"""Task-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NPVJoLtV7imIhemnYfSMjlhVcgz-e75c

CODSOFT(INTERN)

TASK-2

PASSWORD GENERATOR

A password generator is a useful tool that generates strong and random passwords for users. This project aims to create a
password generator application using Python, allowing users to specify the length and complexity of the password.

User Input: Prompt the user to specify the desired length of the password.

Generate Password: Use a combination of random characters to generate a password of the specified length.

Display the Password: Print the generated password on the screen.
"""

import random
import string

def generate_password(length):
    characters = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(random.choice(characters) for _ in range(length))
    return password

def main():
    print("=== Password Generator ===")

    try:
        # Get user input for password length
        length = int(input("Enter the desired length of the password: "))

        if length <= 0:
            print("Password length should be greater than 0.")
        else:
            # Generate and display the password
            password = generate_password(length)
            print("Generated Password:", password)
    except ValueError:
        print("Invalid input. Please enter a valid integer for the password length.")

if __name__ == "__main__":
    main()