# -*- coding: utf-8 -*-
"""Task1(codsoft).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gOpmKM57kG8N9D-cpb1lMS_wprefEWsm

CODSOFT INTERN

TASK-1

CALCULATOR

Design a simple calculator with basic arithmetic operations.
Prompt the user to input two numbers and an operation choice.

Perform the calculation and display the result.
"""

def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
    if y != 0:
        return x / y
    else:
        return "Cannot divide by zero."

# Get user input
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

# Display operation choices
print("Select operation:")
print("1. Add")
print("2. Subtract")
print("3. Multiply")
print("4. Divide")

# Get user choice for operation
choice = input("Enter choice (1, 2, 3, or 4): ")

# Perform the calculation based on user choice
if choice in ('1', '2', '3', '4'):
    if choice == '1':
        result = add(num1, num2)
    elif choice == '2':
        result = subtract(num1, num2)
    elif choice == '3':
        result = multiply(num1, num2)
    elif choice == '4':
        result = divide(num1, num2)

    # Display the result
    print("Result: ", result)

else:
    print("Invalid input. Please enter a valid choice (1, 2, 3, or 4).")